### ISSUE TITLE
Package for Armenian sayings and phrases

### ISSUE THREAD

**Issue by naltun** [kopach/espanso-package-foreign-thanks#1]
https://github.com/naltun/espanso-axper

**Comment by kopach** [comment]
Nice package! Would you like me to add also Armenian "thanks" to this repo? 
Could you, please, help me to understand how it "thanks" will be in Armenian? Based on Google Translate, it's "Շնորհակալություն". Is it correct?

**Comment by naltun** [comment]
@kopach That is indeed correct. 😄 And feel free to add a patch to add it. :) So I must say _Շատ Շնորհակալություն_ to you (Շատ meaning very).

**Comment by kopach** [comment]
done, Շնորհակալություն, @naltun
