### ISSUE TITLE
I am making my own package—

### ISSUE THREAD

**Issue by dhruv-ramu** [kopach/espanso-package-foreign-thanks#17]
Hello,
I am making my own foreign greetings package which will include more than just 'thanks' and will have various other greetings too.
Is it alright if I include thanks in that package?
I can give you write permissions to the repository once it is done as well.

Thanks!

**Comment by kopach** [comment]
Hi @Dhruvsr, thanks for asking. Yes, feel free to use it. Just, please, include reference to this project somewhere in your README. Thanks.

**Comment by dhruv-ramu** [comment]
Sure, I will do that.
