### ISSUE TITLE
Rename "indianthanks" to "hindithanks"

### ISSUE THREAD

**Issue by dhruv-ramu** [kopach/espanso-package-foreign-thanks#2]
The language used here is '_Hindi_', not 'Indian'. That is not a language; there are many languages in India.
Thank you for making this small change.

**Comment by kopach** [comment]
hi @Dhruvsr, thanks for your contribution. Will fix this soon

**Comment by kopach** [comment]
Hi @Dhruvsr fixed and posted new release to Espanso Hub https://github.com/espanso/hub/pull/39 will be available for install once merged there.

If you find this package useful - consider starring this package on [GitHub](https://github.com/kopach/espanso-package-foreign-thanks/stargazers)

[Alco check out my other espanso packages ](https://github.com/kopach?tab=repositories&q=espanso-package&type=source)

**Comment by kopach** [comment]
btw, @Dhruvsr, if you have any other suggestions to this package (e.g. any other language you know) - feel free to raise PR or issue.
